### ISSUE TITLE
Issues with Invalid Automatically Detect Settings URL

### ISSUE THREAD

**Issue by cstack89** [akuhtz/proxy-vole#126]
Hello,

I am having issues with the library at some installations that I believe is caused by the installations having invalid URLs associated with the automatic detection. These are Windows installations where Automatically detect settings and Use Automatic configuration script are enabled. I believe the automatic detect settings URL is invalid, but what I would like is for the library to fall back on the automatic configuration script if that is the case. I believe I see the logic for selecting either the Automatically detect settings URL OR the automatic configuration script in IEProxySearchStrategy createPacSelector. Would it be possible to validate the pacURL if it's not null and then fall back on the autoconfigurl if it is invalid?

I am using version 1.1.5 currently with the IE proxy selector strategy.

**Comment by akuhtz** [comment]
Hello,

Can you provide a stacktrace?

**Comment by akuhtz** [comment]
Close due to no response. Maybe related to #147.
