### ISSUE TITLE
Unexpected proxy auto-detection result on Windows

### ISSUE THREAD

**Issue by vsalavatov** [akuhtz/proxy-vole#147]
A user contacted me today saying that the application does not autodetect proxy settings from the system (Windows 11). The proxy was set to use a PAC script and Chrome detected it successfully. After an investigation it turned out to be the following:
![image](https://github.com/user-attachments/assets/4fdda75a-377e-4210-9e0b-523bd5d581f1)

The user had _both_ the "Automatically detect settings" and "Use setup script" (the PAC thing) configured. With this configuration, proxy-vole failed to detect the PAC script (all strategies didn't find the setting, no errors). With the "Automatically detect settings" toggle turned off, the proxy vole successfully detected the PAC script using the OS_DEFAULT strategy. 

Honestly, I'm not completely sure what the expected behaviour should be in this case. But it might be beneficial to change the behaviour here to find the PAC script. 

Details:
```
Edition	Windows 11 Pro
Version	23H2
```

**Comment by vsalavatov** [comment]
Hi! Default browser in the user's system is Firefox. When we were investigating the issue, we ran the proxy-vole tester on the user's machine and it didn't find anything without any errors:
![telegram-cloud-photo-size-2-5289842396936397582-y](https://github.com/user-attachments/assets/c2d0f85d-64f7-4e4b-8a8f-8210e7654a04)
![telegram-cloud-photo-size-2-5289842396936397581-y](https://github.com/user-attachments/assets/46619c07-fc88-4f04-8f73-f8ef40b5989f)
![telegram-cloud-photo-size-2-5289842396936397580-y](https://github.com/user-attachments/assets/c346da49-e51c-4573-a55b-0d3d02378109)
![telegram-cloud-photo-size-2-5289842396936397579-y](https://github.com/user-attachments/assets/b3444480-fa05-40a0-bffb-80ac94105f81)
![telegram-cloud-photo-size-2-5289842396936397578-y](https://github.com/user-attachments/assets/7affce9a-ed5e-4407-8b68-7021512e64c1)

**Comment by akuhtz** [comment]
@vsalavatov Could you try with the current snapshot?

https://oss.sonatype.org/content/repositories/snapshots/org/bidib/com/github/markusbernhardt/proxy-vole/1.1.6-SNAPSHOT/proxy-vole-1.1.6-20241112.122856-1-jar-with-dependencies.jar

**Comment by boss-chifra** [comment]
Thank you! Your fix helped.
![1 5_not_work](https://github.com/user-attachments/assets/0f4453b1-ddfc-4479-a25a-c1f44a2f1365)
![1 6_work](https://github.com/user-attachments/assets/731993a1-b1aa-49c4-95b7-bdf19ec12ca8)

**Comment by akuhtz** [comment]
@boss-chifra Thanks for the feedback.
