### ISSUE TITLE
Feature request: Make ProxySearch a bit more extendable

### ISSUE THREAD

**Issue by heatzync** [akuhtz/proxy-vole#16]
The `ProxySearch` class only accepts predefined instances of `ProxySearchStrategy` due to the use of the `Strategy` enum.

**Feature request:**

- [ ] Add a `ProxySearch#addStrategy(ProxySearchStrategy custom)` method.

This will allow one to add custom ProxySearchStrategies to the list of possible strategies. I would like to do:

```java
ProxySearch proxySearch = new ProxySearch();

proxySearch.addStrategy(new SomeCustomProxySearchStrategy());
```
Does this make sense or is there a counter argument for why this would be a bad idea?

**Comment by akuhtz** [comment]
@heatzync  Sure. There is a PR (https://github.com/akuhtz/proxy-vole/pull/15) that I prepared from a fork but I haven't merged it yet.
Can you provide a PR with your proposed changes? Maybe you can think about adding to the begin of the list or adding to the end of the list.

**Comment by akuhtz** [comment]
@heatzync I have added new methods to ```ProxySearch```:
```
addStrategy(ProxySearchStrategy custom, boolean addAsFirst);
removeStrategy(Strategy strategy);
```
