### ISSUE TITLE
Change default charset when reading PAC files

### ISSUE THREAD

**Issue by Maxoudela** [akuhtz/proxy-vole#22]
Hi,

First of all, thank you very much for forking and carrying this project, kudos to all of you.

An issue has been raised recently regarding the charset used by Proxy-vole when reading a pac file. By default, we are using the [ISO-8859-1](https://github.com/akuhtz/proxy-vole/blob/d1d1ba6e5e8965ccb01d201094a46aecbfd7e70f/src/main/java/com/github/markusbernhardt/proxy/selector/pac/UrlPacScriptSource.java#L247) charset when reading a file.

If you have a file that has a BOM marker in the beginning, then Java fails at reading it. Technically, BOM should not be present on these files, but sadly I do not control neither can enforce a proper file to my clients.

I wanted to understand why we were doing that, and if we could consider changing it to `UTF-8` which is more universal and will not trigger an error.

**Comment by Maxoudela** [comment]
I've attached a PR that has a faulty file with a BOM. And also an idea of the changes I was thinking of. 

I tested that with JDK 8, therefore I don't know if the issue is gone with a higher JDK because I believe Nashorn was removed and replaced?

Let me know what are your thoughts on that

**Comment by akuhtz** [comment]
Hello,
> 
> 
> I tested that with JDK 8, therefore I don't know if the issue is gone with a higher JDK because I believe Nashorn was removed and replaced?

Yes it was replaced by Rhino because it was deprecated in the JDK.
Yesterday a new release of https://github.com/javadelight/delight-nashorn-sandbox was made that supports the standalone Nashorn version (https://github.com/openjdk/nashorn).
It might be an option to use it. TBH I don't know which one is better.

> 
> Let me know what are your thoughts on that
> 
> EDIT: If we are reluctant on doing such a change, which I can understand, maybe we could provide an API that would allow a developer to change the default charset used when reading file?

It's been in before I forked it. If the tests pass it should not be an issue to change it.

**Comment by Maxoudela** [comment]
Hi,

Actually one test is failing because it's specifically test that `ISO-8859-1` is the default charset.

I did not understood whether you wanted me to create an API and leave `ISO-8859-1` as the default charset, or you have no issue on switching to UTF-8 ?

**Comment by akuhtz** [comment]
Hi,

According to https://en.wikipedia.org/wiki/Proxy_auto-config the
> encoding of PAC scripts is generally unspecified

I adapted the test to check for ```ISO-8859-1``` if specified as ```charset``` parameter.

I think we can switch to UTF-8 and change the version and add this as a change to the README and CHANGELOG.

**Comment by Maxoudela** [comment]
I have update the PR with the corresponding changes. Let me know if I missed something. Thanks a lot

**Comment by akuhtz** [comment]
@Maxoudela I just pushed the release to Maven central repo. Thank you for the PR.
