### ISSUE TITLE
1.0.12 conflicts with Eclipse RCP development

### ISSUE THREAD

**Issue by gschnepp** [akuhtz/proxy-vole#25]
Just to mention that version 1.0.12 changes add an org.jsr305-3.0.2.jar to the dependencies which conflicts - or hides - the javax.annotation package used by Eclipse RCP or plug-in development. This JAR is not there until 1.0.11. Question is, if there's a real need for production.

A full explanation of the problem I ran into can be found here: https://nipafx.dev/jsr-305-java-9/

I still don't really understand 'Java modules' and therefore are lost a little bit finding a solution. I'll stay with 1.0.11 for now to keep my RCP app development running.

**Comment by akuhtz** [comment]
@gschnepp Could you exclude the ```org.eclipse.xtend.lib``` dependency and test if this works for you?

```
<dependency>
   <groupId>org.bidib.com.github.markusbernhardt</groupId>
   <artifactId>proxy-vole</artifactId>
   <version>${proxy-vole.version}</version>
   <exclusions>
      <exclusion>
         <groupId>org.eclipse.xtend</groupId>
         <artifactId>org.eclipse.xtend.lib</artifactId>
      </exclusion>
   </exclusions>
</dependency>
```

**Comment by gschnepp** [comment]
Andreas, thanks so far: I'm not sure if XTend is an optional package in delight-rhino-sandbox, so I opened an issue there to find out: [https://github.com/javadelight/delight-rhino-sandbox/issues/21)

It also works if I repackage Guava with ";resolution:=optional" setting like it was until Guava 21.0 (in delight-rhino-sandbox 0.0.13). Not sure if this is a good idea anyway... (Guava developers might have had a reason for that change.)

**Comment by gschnepp** [comment]
@akuhtz mxro from java-delight has created a new release 0.0.15 without XTend, Guava and other dependencies. They are just not needed any longer, also not JSR305.

**Comment by akuhtz** [comment]
@gschnepp Are the file other than the ```pom.xml``` intended to be changed? Looks like reformatted with unwanted changes.

**Comment by gschnepp** [comment]
For this only pom.xml change is really required. DHCPOptions.java has/had three unneccessary boxings, too ("new Byte(byte)"), which can remain. The rest is reformatted by IDE automatically, you're right.

It's the second pull request of my life on github, so I have no real clue on how to change that actually. Do I need to change the PR?

**Comment by gschnepp** [comment]
Reverted automatic IDE changes in PR just leaving pom.xml changed

**Comment by akuhtz** [comment]
@gschnepp Release 1.0.13 is published to maven central. Thank you for open this issue and providing the PR.
