### ISSUE TITLE
XML security flags dependent on system property

### ISSUE THREAD

**Issue by ThomasGaebler** [akuhtz/proxy-vole#32]
Hi,

is it possible to set the xml security flags dependent on a system property?

The used xml constants are unknown on wildfly 23 (Java 11) in the classes GnomeProxySearchStrategy and PListParser:
 
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            documentBuilderFactory.setAttribute( XMLConstants.ACCESS_EXTERNAL_DTD, "" );
            documentBuilderFactory.setAttribute( XMLConstants.ACCESS_EXTERNAL_SCHEMA, "" );

An exception is thrown:

            java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	            at deployment....//org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	            at deployment....//com.github.markusbernhardt.proxy.util.PListParser.parse(PListParser.java:274)

An option is to handle it with a system property like:

            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            if ( Boolean.getBoolean( "proxy-vole.xml.factory.feature.secure.processing" ) )
            {
                documentBuilderFactory.setFeature( XMLConstants.FEATURE_SECURE_PROCESSING, true );
            }
            else
            {
                documentBuilderFactory.setAttribute( XMLConstants.ACCESS_EXTERNAL_DTD, "" );
                documentBuilderFactory.setAttribute( XMLConstants.ACCESS_EXTERNAL_SCHEMA, "" );
            }

Is it possible to implement this?

Greetings, Thomas

**Comment by akuhtz** [comment]
@ThomasGaebler Sure. Can you provide a PR?

**Comment by ThomasGaebler** [comment]
Thanks for approval and merging. Is there already a release plan for the next version?

Greetings, Thomas

**Comment by akuhtz** [comment]
@ThomasGaebler Thanks for the PR :+1: I can do a release later today or tomorrow.

**Comment by ThomasGaebler** [comment]
Very nice, thank you!

**Comment by akuhtz** [comment]
@ThomasGaebler proxy-vole-1.0.15 is released and available on Maven Central.
