### ISSUE TITLE
NullPointerException in OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:117)

### ISSUE THREAD

**Issue by vladimirkondratyev** [akuhtz/proxy-vole#35]
The problem is reproducible on macOS 12.0.1 Monterey. It seems that parser of /Library/Preferences/SystemConfiguration/preferences.plist file does not expects at line OsxProxySearchStrategy.java:117 that the returned "selectedServiceSettings" dictionary might be null.

JDK: 11.0.12
VM: OpenJDK 64-Bit Server VM
Vendor: JetBrains s.r.o.
OS: Mac OS X
OS version: 12.0.1
OS arch: x86_64
Date and time: 2021-11-10 09:16:44

Caused by: java.lang.NullPointerException
at com.github.markusbernhardt.proxy.search.desktop.osx.OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:117)
at com.github.markusbernhardt.proxy.search.desktop.DesktopProxySearchStrategy.getProxySelector(DesktopProxySearchStrategy.java:38)
at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxProxySearchStrategy.getProxySelector(FirefoxProxySearchStrategy.java:113)
at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:222)
@vladimirkondratyev

**Comment by akuhtz** [comment]
@vladimirkondratyev Can you try with proxy-vole:1.0.16-SNAPSHOT ?

**Comment by nedtwigg** [comment]
I tested it, confirmed fixed.

**Comment by akuhtz** [comment]
@nedtwigg Thanks for testing.

**Comment by vladimirkondratyev** [comment]
I'm sorry for stupid questions, but what is Maven repository URL to download 1.0.16-SNAPSHOT?

**Comment by akuhtz** [comment]
Not a stuipid question :-)

Add this SNAPSHOT repo to the ```repositories``` section of your ```pom.xml``` :
```
        <repository>
            <id>sonatype-snapshots</id>
            <name>Sonatype Snapshot Plugin repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```
It's just for testing and you can remove it once the fix is confirmed as I will do a release.

If you have not specified the ```repositories``` section in your ```pom.xml``` yet, this is the complete one:
```
    <repositories>
        <repository>
            <id>central</id>
            <name>Maven2 central repository</name>
            <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
            <id>sonatype-snapshots</id>
            <name>Sonatype Snapshot Plugin repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        </repository>
    </repositories>
```

**Comment by vladimirkondratyev** [comment]
I confirm that there is no NPE in 1.0.16-SNAPSHOT. Unfortunately I cannot test further, that the method returns proper proxy selector. The issue happened in a wild, and all I have is the end-user's preferences.plist.

BTW, it would be very helpful, if com.github.markusbernhardt.proxy.ProxySearch in addition to addStrategy(ProxySearch.Strategy) method, has method addStrategy() which take ProxySearchStrategy as a parameter. It would give an ability to override it and wrap strategies to "safe" wrapper, which gracefully handles non-expected RuntimeExceptions. Current design is very rigid, so I had to copy-paste entire ProxySearch just to catch exception inside getProxySelector().

**Comment by akuhtz** [comment]
> BTW, it would be very helpful, if com.github.markusbernhardt.proxy.ProxySearch in addition to addStrategy(ProxySearch.Strategy) method, has method addStrategy() which take ProxySearchStrategy as a parameter. It would give an ability to override it and wrap strategies to "safe" wrapper, which gracefully handles non-expected RuntimeExceptions. Current design is very rigid, so I had to copy-paste entire ProxySearch just to catch exception inside getProxySelector().

This should now be possible with 1.0.17-SNAPSHOT as part of #16
