### ISSUE TITLE
FirefoxProxySearchStrategy incorrectly detects active user profile

### ISSUE THREAD

**Issue by vladimirkondratyev** [akuhtz/proxy-vole#36]
FirefoxProxySearchStrategy does not find proxy specified in FireFox settings. I'm running Ubuntu 21.04 and FireFox 94.0. The content of my ~/.mozilla/firefox/profiles.ini is below. 

The problem is that FirefoxProxySearchStrategy detects profile "p6y3k23k.default" as the default one, then it tries to read file ~/.mozilla/firefox/p6y3k23k.default/prefs.js and fails dues to the file is missing.

But the actual active profile is "bk6on8rm.default-release". It is marked with "Locked=1" property. I've found the article on Mozilla that describes the logic https://support.mozilla.org/en-US/kb/understanding-depth-profile-installation

----------------------------------------------------------------------------------------------------

[Install4F96D1932A9F858E]
Default=bk6on8rm.default-release
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=p6y3k23k.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=bk6on8rm.default-release

[General]
StartWithLastProfile=1
Version=2

**Comment by akuhtz** [comment]
@vladimirkondratyev Can you try with the latest snapshot if the issue is fixed?

**Comment by vladimirkondratyev** [comment]
I confirm that proxy-vole:1.0.16-SNAPSHOT works like a charm, and FirefoxProxySearchStrategy returns correct proxy selector for HTTP and HTTPS protocols. I tests on Ubuntu 21.04 + FF 94.0. Thanks for the fix.

**Comment by akuhtz** [comment]
@vladimirkondratyev proxy-vole:1.0.16 with this fix is released.
