### ISSUE TITLE
Release with JNA 5.11.0?

### ISSUE THREAD

**Issue by nlmarco** [akuhtz/proxy-vole#39]
Dear Andreas,

thanks a lot for taking care of this project!

We lately ran into an issue with two of our dependencies needing different JNA-versions. Thus, we need a proxy-vole-release with JNA 5.11.0. I saw that you just upgraded the dependency to exactly this version a week ago. That's perfect.

When do you plan the next release?

Cheers, Marco :-)

**Comment by akuhtz** [comment]
Hello Marco.

Released with ```1.0.17``` a few minutes ago.

**Comment by nlmarco** [comment]
Thanks a lot! This was really fast :-)
